name: add event

on:
  issues
  
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
#        with:
#          submodules: true  # Fetch Hugo themes (true OR recursive)
#          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: add event to my blog
        uses: fzdwx/add-event-to-myblog@v2.9.4
        with:
          # the repo PAT or GITHUB_TOKEN
          token: ${{ secrets.TOKEN }}
          issueNumber: ${{ github.event.issue.number }}
          username: github.action
          email: action@github.com
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: build
        run: hugo --minify

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
